vimd modifications
- auto build container if it does not exist
- Add default locale to container
- Update vim terminal shell
- Add flag for changing container user via cli
- Install correct version of jq
- Fix --bindir when installing gems

diff --git a/extras/vimd/vimd-exec b/extras/vimd/vimd-exec
--- a/extras/vimd/vimd-exec
+++ b/extras/vimd/vimd-exec
@@ -1,13 +1,43 @@
 #!/usr/bin/env bash
 set -e
-[ -z "$1" ] && { echo "Error: You must specify a command" >&2; exit 1; }
 
-DOCKER_IMAGE=vim-ale-linters:v1
+# Find directory that this script is in
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+# Default to mounting the current working directory
 BASEDIR=$PWD
+
+# TODO:
+# Collect all mount volumes and find the lowest common denominators
+# - Look for common root paths and deduplicate them
+# - Check each common root path for git repository membership and trim the
+#   mount path back to the root.
+
+# The docker image that we should use
+DOCKER_IMAGE=vim-ale-linters:v1
+
+has_image=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep $DOCKER_IMAGE && echo 'yes' || echo 'no')
+
+if [ "$has_image" == 'no' ]; then
+  echo Building docker image: $DOCKER_IMAGE
+  $SCRIPT_DIR/vimd-build
+fi
 
 # Source the vimdrc file for customization options
 VIMD_OPTS=""
-[ -e "$HOME/.vimd" ] && source "$HOME/.vimdirc"
+[ -e "$HOME/.vimdrc" ] && source "$HOME/.vimdrc"
+
+
+# If the first parameter is a flag; then consume it and forward the rest of the
+# parameters
+APP_USER='app'
+if [ "$1" == "--user" ]; then
+  APP_USER="$2"
+  shift
+  shift
+fi
+
+[ -z "$1" ] && { echo "Error: You must specify a command" >&2; exit 1; }
 
 ##
 # Forward all parameters to the docker container
@@ -49,14 +79,20 @@ done
 # Avoid mounting anything from $HOME because it will already be mounted
 MOUNT_OPTS="-v $BASEDIR:$BASEDIR"
 [[ "$BASEDIR" == $HOME* ]] && MOUNT_OPTS=""
+# TODO: This is a hack to avoid mounts from vimdrc file
+[[ "$BASEDIR" == /work* ]] && MOUNT_OPTS=""
 MOUNT_OPTS="$MOUNT_OPTS -v $HOME:$HOME"
 
 # Command to fix permissions inside of docker container
-CMD_PERMS="usermod -u $(id -u) app; usermod -g $(id -g) app"
+CMD_PERMS="usermod -u $(id -u) $APP_USER; usermod -g $(id -g) $APP_USER"
 
 # Join array with spaces
-ARGS=$(IFS=" " ; echo "cd $BASEDIR; $CMD_PERMS; su -m app -c '${ARGS[@]}'")
-
+if [ "$APP_USER" != "root" ]; then
+  # run command as a different user by default
+  ARGS=$(IFS=" " ; echo "cd $BASEDIR; $CMD_PERMS; su -m $APP_USER -c '${ARGS[@]}'")
+else
+  ARGS=$(IFS=" " ; echo "cd $BASEDIR; echo WARNING: unable to update ID/GID for root user; ${ARGS[@]}")
+fi
 # Print out command that we exec
 set -o xtrace
 
@@ -66,4 +102,4 @@ docker run --rm -it \
   $MOUNT_OPTS \
   $VIMD_OPTS \
   --user root \
-  $DOCKER_IMAGE bash -c "${ARGS[@]}"
+  $DOCKER_IMAGE bash -c "$ARGS"
